In [3]:
import numpy as np

### 1. Import numpy as np and see the version

1. Q. Import numpy as np and print the version number.

In [4]:
import numpy as np
np.version.version

'1.16.5'

### 2. How to create a 1D array?

2. Q. Create a 1D array of numbers from 0 to 9
#### array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
s = np.array([0,1,2,3,4,5,6,7,8,9],dtype=np.int)
print(s)

[0 1 2 3 4 5 6 7 8 9]


### 3. How to create a boolean array?

3. Q. Create a 3×3 numpy array of all True’s

In [6]:
s = np.array([(3,3),'a',True,False],dtype=np.bool)
print(s)

[ True  True  True False]


### 4. How to extract items that satisfy a given condition from 1D array?

4. Q. Extract all odd numbers from arr  
##### Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired output: #> array([1, 3, 5, 7, 9])

In [7]:
 s = np.arange(0,10)
print(s)
s= s[s%2 !=0]
s

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

### 5. How to replace items that satisfy a condition with another value in numpy array?

5. Q. Replace all odd numbers in arr with -1  
##### Input: >  arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired Output:> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


In [15]:
s = np.arange(10)
indices = [1,3,5,7,9,]
r = s[indices]
r[0]= -1
s
s[indices] = -1
s

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 6. How to replace items that satisfy a condition without affecting the original array?

6. Q. Replace all even numbers in arr with 0 without changing arr
##### Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### out>  array([ 0, 0,  2, 0,  4, 0,  6, 0,  8, 0])


In [16]:
s = np.arange(10)
indices = [0,1,3,5,7,9,]
r = s[indices]
r[0]= 0
s
s[indices] = 0
s

array([0, 0, 2, 0, 4, 0, 6, 0, 8, 0])

### 7. How to reshape an array?
7. Q. Convert a 1D array to a 2D array with 2 rows
##### Input: np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
##### Desired Output:
#> array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])


In [26]:
s =np.arange(10)
s = np.array(s)
s
s = np.array([0,1,2,3,4,5,6,7,8,9],dtype='<U1')
s.reshape(-1,2)
s

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U1')

### 8. How to stack two arrays vertically?
8. Q. Stack arrays a and b vertically
Input  
a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)  
Desired Output:  
#> array([[0, 1, 2, 3, 4],  
#>        [5, 6, 7, 8, 9],  
#>        [1, 1, 1, 1, 1],  
#>        [1, 1, 1, 1, 1]])


In [31]:
s = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
s = np.vstack((s,b))
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 9. How to stack two arrays horizontally?
9. Q. Stack the arrays a and b horizontally.
##### Input  
a = np.arange(10).reshape(2,-1)  
b = np.repeat(1, 10).reshape(2,-1)  
##### Desired Output:  
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],  
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])


In [33]:
s = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
s = np.hstack((s,b))
s

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 10. How to generate custom sequences in numpy without hardcoding?
1. Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
##### Input:  
a = np.array([1,2,3])
##### Desired Output:  
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [52]:
s = np.array([1,2,3])
np.r_[np.repeat(s,3),np.tile(s,3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. How to get the common items between two python numpy arrays?
11. Q. Get the common items between a and b
#### Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])
##### Desired Output:
array([2, 4])


In [54]:
s = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(s,b)

array([2, 4])

### 12. How to remove from one array those items that exist in another?
12. Q. From array a remove all items present in array b

##### Input:
a = np.array([1,2,3,4,5])  
b = np.array([5,6,7,8,9])
##### Desired Output:  
array([1,2,3,4])


In [55]:
s = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(s,b)

array([1, 2, 3, 4])

### 13. How to get the positions where elements of two arrays match?
13. Q. Get the positions where elements of a and b match
##### Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])
##### Desired Output:
#> array([1, 3, 5, 7])


In [56]:
s = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(s==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. How to extract all numbers between a given range from a numpy array?
14. Q. Get all items between 5 and 10 from a.

##### Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])
###### Desired Output:

#> array([6, 9, 10])

In [57]:
s = np.array([2, 6, 1, 9, 10, 3, 27])
s[(s>=5)&(s<=10)]

array([ 6,  9, 10])

### 15. How to make a python function that handles scalars to work on numpy arrays?
15. Q. Convert the function maxx that works on two scalars, to work on two arrays.

##### Input: 

In [62]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)



5

###### Desired Output:
a = np.array([5, 7, 9, 8, 6, 4, 5])  
b = np.array([6, 3, 4, 8, 9, 7, 1])  
pair_max(a, b)  
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [67]:
pair_max=np.vectorize(maxx,otypes=[float])
display(a,b)

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

### 16. How to swap two columns in a 2d numpy array?
16.Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr


In [71]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 17. How to swap two rows in a 2d numpy array?
17.Q. Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)  
arr



In [73]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#Calcul de la vitesse (vitesse=distance//temps)
distance=(19.7)
temps=(6.892)
vitesse=19.7/6.892
print("Resultat :",vitesse)

Resultat : 2.8583865351131745


In [5]:
#afficher non et l'age
nom= input("Le Nom est ")
age= input("L'age est  ")
print(nom,age)

Le Nom est Yvel Marcelin
L'age est  28 ans
Yvel Marcelin 28 ans


In [16]:
##Securiser une pression d'un seuil
ps=(2.3)
vs=(7.41)
pc=input("Entre la valeur Pression Courrant : ")
pc=(float)
vc=input("Entrer la valeur Volume Courrant : ")
vc= (float)
if (vc >= vs) and (pc >= ps):
    print('Attention diminuer la pression {} et le volume {}: '.format(pc, vc))
elif (pc >= ps):
    print('Attentionn diminuer la pression du seuil {}: '.format(pc))
elif (vc >= vs):
    print('Attention diminuer le volume {}'.format(vc))
else:
    print("L'enceinte est stable bravo....!")
        



Entre la valeur Pression Courrant : 4
Entrer la valeur Volume Courrant : 52


TypeError: '>=' not supported between instances of 'type' and 'float'

In [1]:
a = 0
b = 10
while a < b:
    print("la Valeur de a {}".format(a))
    a+=1

la Valeur de a 0
la Valeur de a 1
la Valeur de a 2
la Valeur de a 3
la Valeur de a 4
la Valeur de a 5
la Valeur de a 6
la Valeur de a 7
la Valeur de a 8
la Valeur de a 9
